pipeline {
    agent {
        node {
            label 'worker' 
        }
   }

    stages {
        stage('Docker login') {
            steps {
                sh 'echo $DOCKERHUB_TOKEN | docker login -u denisvoznik --password-stdin'
                sh 'echo ${GIT_BRANCH}'
            }
        }
        stage('Docker build') {
            steps{
                sh 'docker build -t terraform .'
            }
        }
        stage('Docker tag and push') {
            steps {
                sh """
                    docker tag terraform denisvoznik/terraform-dz:${GIT_BRANCH}
                    docker push denisvoznik/terraform-dz:${GIT_BRANCH}
                """
            }
        }
    }
}
