pipeline {
    agent {
        node {
            label 'worker' 
        }
   }

    stages {
        stage('Docker login') {
             steps {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_TOKEN')]) {
                sh 'echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin'
                }
            }
        }
        stage('Docker build') {
            steps{
                sh 'docker build -t terraform .'
            }
        }
        stage('Docker tag and push') {
            steps {
                sh """
                    short_branch=${GIT_BRANCH}
                    short_branch=${short_branch##origin/}
                    docker tag terraform denisvoznik/terraform-dz
                    docker push denisvoznik/terraform-dz:${GIT_BRANCH}
                """
            }
        }
    }
}
